### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by textbrowser** [maandree/sha3sum#15]
This is only a request.

Would a test suite be helpful? Perhaps someone would like to validate your implementation.

**Comment by maandree** [comment]
Tests are found in libkeccak (https://github.com/maandree/libkeccak/blob/master/src/test.c),
so to test this program you whould just need too test it against a few hashes tested in libkeccak
and then verify that libkeccaks tests are correct, or add your own testes to libkeccak.
Perhaps this should mentioned in the readme.

**Comment by textbrowser** [comment]
Very good. Please close.
