### ISSUE TITLE
Compiler error: 'libkeccak.h' file not found

### ISSUE THREAD

**Issue by ajbhatia-visa** [maandree/sha3sum#19]
Getting error for libkeccak.h file not being found, when I run `make install-all`. Could be the wrong way to do a build. Did not find any instructions for building.

    %> make install-all
    cc -Wall -Wextra -pedantic -Wdouble-promotion -Wformat=2 -Winit-self -Wmissing-include-dirs
    -Wtrampolines -Wfloat-equal -Wshadow -Wmissing-prototypes -Wmissing-declarations
    -Wredundant-decls -Wnested-externs -Winline -Wno-variadic-macros -Wswitch-default
    -Wpadded -Wsync-nand -Wunsafe-loop-optimizations -Wcast-align -Wstrict-overflow
    -Wdeclaration-after-statement -Wundef -Wbad-function-cast -Wcast-qual -Wlogical-op
    -Wstrict-prototypes -Wold-style-definition -Wpacked -Wvector-operation-performance
    -Wunsuffixed-float-constants -Wsuggest-attribute=const -Wsuggest-attribute=noreturn
    -Wsuggest-attribute=pure -Wsuggest-attribute=format -Wnormalized=nfkc -std=gnu99 -O3 -c
    -o obj/keccak-224sum.o src/keccak-224sum.c
    warning: unknown warning option '-Wtrampolines' [-Wunknown-warning-option]
    warning: unknown warning option '-Wsync-nand' [-Wunknown-warning-option]
    warning: unknown warning option '-Wunsafe-loop-optimizations'; did you mean '-Wunavailable-declarations'? [-Wunknown-warning-option]
    warning: unknown warning option '-Wlogical-op'; did you mean '-Wliblto'? [-Wunknown-warning-option]
    warning: unknown warning option '-Wvector-operation-performance' [-Wunknown-warning-option]
    warning: unknown warning option '-Wunsuffixed-float-constants' [-Wunknown-warning-option]
    warning: unknown warning option '-Wsuggest-attribute=const' [-Wunknown-warning-option]
    warning: unknown warning option '-Wsuggest-attribute=noreturn' [-Wunknown-warning-option]
    warning: unknown warning option '-Wsuggest-attribute=pure'; did you mean '-WNSObject-attribute'? [-Wunknown-warning-option]
    warning: unknown warning option '-Wsuggest-attribute=format'; did you mean '-Wproperty-attribute-mismatch'? [-Wunknown-warning-option]
    warning: unknown warning option '-Wnormalized=nfkc'; did you mean '-Wformat-pedantic'? [-Wunknown-warning-option]
    In file included from src/keccak-224sum.c:19:
    src/common.h:23:10: fatal error: 'libkeccak.h' file not found
    #include <libkeccak.h>
             ^
    11 warnings and 1 error generated.
    make: *** [obj/keccak-224sum.o] Error 1

**Comment by maandree** [comment]
Have you installed libkeccak?

**Comment by ajbhatia-visa** [comment]
No. How do I do that? And thanks for your help.

**Comment by maandree** [comment]
```
git clone https://github.com/maandree/libkeccak
cd libkeccak
make install PREFIX=/usr/local
sudo make install PREFIX=/usr/local
```

**Comment by ajbhatia-visa** [comment]
Got an error buiding libkeccak. After many warnings (including warnings about unknown warning options), got the following error (Added extra newlines for readability):

    cc -std=gnu99 -Wall -Wextra -pedantic -Wdouble-promotion -Wformat=2 -Winit-self
    -Wmissing-include-dirs -Wtrampolines -Wfloat-equal -Wshadow -Wmissing-prototypes
    -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -Wno-variadic-macros
    -Wswitch-default -Wpadded -Wsync-nand -Wunsafe-loop-optimizations -Wcast-align
    -Wstrict-overflow -Wdeclaration-after-statement -Wundef -Wbad-function-cast -Wcast-qual
    -Wwrite-strings -Wlogical-op -Waggregate-return -Wstrict-prototypes -Wold-style-definition
    -Wpacked -Wvector-operation-performance -Wunsuffixed-float-constants -Wsuggest-attribute=const
    -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wsuggest-attribute=format
    -Wnormalized=nfkc  -shared
    -Wl,-soname,libkeccak.so.1 -o bin/libkeccak.so.1.1 obj/libkeccak/digest.o obj/libkeccak/files.o
    obj/libkeccak/generalised-spec.o obj/libkeccak/hex.o obj/libkeccak/state.o
    obj/libkeccak/mac/hmac.o 
    ld: unknown option: -soname
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [bin/libkeccak.so.1.1] Error 1

**Comment by ajbhatia-visa** [comment]
I see that `cc` on my machine is coming from `/usr/local/opt/ccache/libexec/cc`, which is a link to `/usr/local/opt/ccache/bin/ccache`

That could be the problem.

**Comment by maandree** [comment]
I haven't seen that error before. What operating system are you using?

**Comment by ajbhatia-visa** [comment]
Mac OS X El Capitan 10.11.6

    %> uname -a
    Darwin WM-C02RX16QG8WM 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

**Comment by maandree** [comment]
If I recall correctly, libraries aren't linked the same why on OS X, and I have only written the make file to support Linux. I will take a look at what changes are necessary for OS X.

**Comment by maandree** [comment]
I think you should change all `.so` in the makefile to `.dylib` and change
```
$(CC) $(FLAGS) $(LDOPTIMISE) -shared -Wl,-soname,libkeccak.so.$(LIB_MAJOR) -o $@ $^ $(LDFLAGS)
```
(https://github.com/maandree/libkeccak/blob/master/Makefile#L147)
to
```
$(CC) $(FLAGS) $(LDOPTIMISE) -dynamiclib -o $@ $^ $(LDFLAGS)
```

**Comment by ajbhatia-visa** [comment]
I got a successful build, finally. Besides the above, I had to make some other changes to `Makefile` and also install `argparser` and `auto-auto-complete` (which required some changes in their `Makefile`s, too. Also, I did not build the documentation targets which had other dependencies. I tried to install MacTex but the package is too large for brew to install. There are other ways to install it but I did not need the docs enough to spend more time on that.

Thanks a lot for your help.

**Comment by ajbhatia-visa** [comment]
If you would like, I can send you the `diff`s of my changes.

**Comment by maandree** [comment]
That would be great.

**Comment by ajbhatia-visa** [comment]
Here is a zip file with diffs of Makefiles of argparser, auto-auto-complete, libkeccak and sha3sum. I can only say that they work on MacOS 10.11.6. You can take what you want from here to make yours work with both Linux and MacOS.

[for-maandree.zip](https://github.com/maandree/sha3sum/files/1113704/for-maandree.zip)

**Comment by vikas1188** [comment]
Hi @ajbhatia-visa ,
I'm able to build the libkeccak on my linux (ubuntu). Can you help me with the 

> argparse

 I'm having a hard time to configure it and making this sha3sum up and running.

**Comment by tommypeps** [comment]
hi @ajbhatia-visa  I make all correction of file for-maandree.zip and I have this return 

`
 make install-all
cc -Wall -Wextra -pedantic -Wdouble-promotion -Wformat=2 -Winit-self -Wmissing-include-dirs -Wtrampolines -Wfloat-equal -Wshadow -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -Wno-variadic-macros -Wswitch-default -Wpadded -Wsync-nand -Wunsafe-loop-optimizations -Wcast-align -Wstrict-overflow -Wdeclaration-after-statement -Wundef -Wbad-function-cast -Wcast-qual -Wlogical-op -Wstrict-prototypes -Wold-style-definition -Wpacked -Wvector-operation-performance -Wunsuffixed-float-constants -Wsuggest-attribute=const -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wsuggest-attribute=format -Wnormalized=nfkc -std=gnu99 -O3 -c -o obj/keccak-224sum.o src/keccak-224sum.c  
warning: unknown warning option '-Wtrampolines' [-Wunknown-warning-option]
warning: unknown warning option '-Wsync-nand' [-Wunknown-warning-option]
warning: unknown warning option '-Wunsafe-loop-optimizations'; did you mean '-Wunavailable-declarations'? [-Wunknown-warning-option]
warning: unknown warning option '-Wlogical-op'; did you mean '-Wliblto'? [-Wunknown-warning-option]
warning: unknown warning option '-Wvector-operation-performance' [-Wunknown-warning-option]
warning: unknown warning option '-Wunsuffixed-float-constants' [-Wunknown-warning-option]
warning: unknown warning option '-Wsuggest-attribute=const' [-Wunknown-warning-option]
warning: unknown warning option '-Wsuggest-attribute=noreturn' [-Wunknown-warning-option]
warning: unknown warning option '-Wsuggest-attribute=pure'; did you mean '-WNSObject-attribute'? [-Wunknown-warning-option]
warning: unknown warning option '-Wsuggest-attribute=format'; did you mean '-Wproperty-attribute-mismatch'? [-Wunknown-warning-option]
warning: unknown warning option '-Wnormalized=nfkc'; did you mean '-Wformat-pedantic'? [-Wunknown-warning-option]
In file included from src/keccak-224sum.c:19:
In file included from src/common.h:23:
In file included from src/libkeccak.h:24:
src/libkeccak/generalised-spec.h:154:35: warning: unknown attribute 'leaf' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull, nothrow)))
                                  ^
In file included from src/keccak-224sum.c:19:
In file included from src/common.h:23:
In file included from src/libkeccak.h:25:
src/libkeccak/state.h:112:35: warning: unknown attribute 'leaf' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull)))
                                  ^
src/libkeccak/state.h:150:59: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull, nothrow, optimize("-O0"))))
                                                          ^
src/libkeccak/state.h:150:35: warning: unknown attribute 'leaf' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull, nothrow, optimize("-O0"))))
                                  ^
src/libkeccak/state.h:158:59: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull, nothrow, optimize("-O0"))))
                                                          ^
src/libkeccak/state.h:158:35: warning: unknown attribute 'leaf' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull, nothrow, optimize("-O0"))))
                                  ^
src/libkeccak/state.h:166:53: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((nonnull, nothrow, optimize("-O0"))))
                                                    ^
src/libkeccak/state.h:175:43: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((unused, optimize("-O0"))))
                                          ^
src/libkeccak/state.h:224:43: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((unused, optimize("-O0"))))
                                          ^
src/libkeccak/state.h:247:35: warning: unknown attribute 'leaf' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull)))
                                  ^
src/libkeccak/state.h:291:35: warning: unknown attribute 'leaf' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull, nothrow)))
                                  ^
src/libkeccak/state.h:302:35: warning: unknown attribute 'leaf' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull)))
                                  ^
src/libkeccak/state.h:313:35: warning: unknown attribute 'leaf' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull, nothrow, warn_unused_result, pure)))
                                  ^
In file included from src/keccak-224sum.c:19:
In file included from src/common.h:23:
In file included from src/libkeccak.h:27:
src/libkeccak/hex.h:35:35: warning: unknown attribute 'leaf' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull, nothrow)))
                                  ^
src/libkeccak/hex.h:46:35: warning: unknown attribute 'leaf' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull, nothrow)))
                                  ^
src/libkeccak/hex.h:57:35: warning: unknown attribute 'leaf' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((leaf, nonnull, nothrow)))
                                  ^
In file included from src/keccak-224sum.c:19:
In file included from src/common.h:23:
In file included from src/libkeccak/../libkeccak.h:28:
src/libkeccak/files.h:56:50: warning: unknown attribute 'artificial' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((nonnull(2, 3), artificial, gnu_inline)))
                                                 ^
src/libkeccak/files.h:76:47: warning: unknown attribute 'artificial' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((nonnull(2), artificial, gnu_inline)))
                                              ^
src/libkeccak/files.h:99:47: warning: unknown attribute 'artificial' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((nonnull(2), artificial, gnu_inline)))
                                              ^
src/libkeccak/files.h:122:47: warning: unknown attribute 'artificial' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((nonnull(2), artificial, gnu_inline)))
                                              ^
In file included from src/keccak-224sum.c:19:
In file included from src/common.h:23:
In file included from src/libkeccak/../libkeccak.h:29:
src/libkeccak/mac/hmac.h:172:53: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((nonnull, nothrow, optimize("-O0"))))
                                                    ^
src/libkeccak/mac/hmac.h:201:43: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((unused, optimize("-O0"))))
                                          ^
src/libkeccak/mac/hmac.h:238:43: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
LIBKECCAK_GCC_ONLY(__attribute__((unused, optimize("-O0"))))
                                          ^
src/libkeccak/mac/hmac.h:312:4: warning: cast from 'char *' to 'size_t *' (aka 'unsigned long *') increases required alignment from 1 to 8
      [-Wcast-align]
  *(size_t*)data = state->key_length;
   ^~~~~~~~~~~~~
src/libkeccak/mac/hmac.h:346:35: warning: cast from 'const char *' to 'const size_t *' (aka 'const unsigned long *') increases required
      alignment from 1 to 8 [-Wcast-align]
  return skip + sizeof(size_t) + *(const size_t*)data + 2 * sizeof(char);
                                  ^~~~~~~~~~~~~~~~~~~
src/keccak-224sum.c:28:10: warning: implicit declaration of function 'args_init' is invalid in C99 [-Wimplicit-function-declaration]
  return RUN("Keccak", "keccak-224sum", LIBKECCAK_KECCAK_SUFFIX);
         ^
src/common.h:40:4: note: expanded from macro 'RUN'
  (args_init(algo " checksum calculator",                       \
   ^
src/keccak-224sum.c:28:10: error: use of undeclared identifier 'args_standard_abbreviations'
src/common.h:42:19: note: expanded from macro 'RUN'
             NULL, 1, 0, args_standard_abbreviations),          \
                         ^
37 warnings and 1 error generated.
make: *** [obj/keccak-224sum.o] Error 1



`


Someone Find de solution ?

I dont understand: the error args_standard_abbreviations

Thanks

**Comment by ajoybhatia** [comment]
I do not know why or how the date when this issue was opened and conversation started is shown as Jun 27, 2017. This is something I worked on last year, sometime between Aug 15 and Dec 31. It's not as if it's just the year that is wrong because it was definitely after Aug 1, 2016.

Anyway, I am now on to other things and I don't think I can recreate the context or get the time to look into this. One thing I can say is that I did not necessarily make all targets. I did just what was necessary to get sha3sum working. For instance, I did not need doc or tex info etc. So just try to build what is needed and, if there are any errors, do not be afraid to look into the makefile and code to see what changes are needed.

**Comment by ajoybhatia** [comment]
A clarification: ajoybhatia is my personal account but I am the same person as ajbhatia-visa. Did not notice when posting previous comment that I was logged in as 'ajoybhatia' and not 'ajbhatia-visa'.

**Comment by ajbhatia-visa** [comment]
I do not know why or how the date when this issue was opened and conversation started is shown as Jun 27, 2017. This is something I worked on last year, sometime between Aug 15 and Dec 31. It's not as if it's just the year that is wrong because it was definitely after Aug 1, 2016.

Anyway, I am now on to other things and I don't think I can recreate the context or get the time to look into this. One thing I can say is that I did not necessarily make all targets. I did just what was necessary to get sha3sum working. For instance, I did not need doc or tex info etc. So just try to build what is needed and, if there are any errors, do not be afraid to look into the makefile and code to see what changes are needed.

**Comment by maandree** [comment]
I've made some changes. The only dependency now is libkeccak, which should be built with `LIBEXT=dylib LIBFLAGS=-dynamiclib` on MacOS. However, if you are using a compiler that pretends to be GCC (such as clang), you may need to remove some arguments to `__attribute__`s in libkeccak, I'm not going to fix this, as this is clearly an issue with such compilers (if the compiler pretends to be another compiler they should ignore attributes they don't support unless they change the behaviour).
