### ISSUE TITLE
libkeccak.so.1 error

### ISSUE THREAD

**Issue by hipokito** [maandree/sha3sum#22]
After installing libkeccak:
~/Desktop/test$ git clone https://github.com/maandree/libkeccak
~/Desktop/test$ cd libkeccak/
~/Desktop/test/libkeccak$ make

And after installing sha3sum:
~/Desktop/test$ git clone https://github.com/maandree/sha3sum.git
~/Desktop/test$ cd sha3sum/
~/Desktop/test/sha3sum$ make

There are no errors in installation logs but when I try to run: 

~/Desktop/test/sha3sum$ keccak-256sum I get the following exception:
keccak-256sum: error while loading shared libraries: libkeccak.so.1: cannot open shared object file: No such file or directory

Could it be because I am using a 32bit Ubuntu but this is intended for 64bit?

**Comment by maandree** [comment]
Unless you run `sudo make install PREFIX=/usr` for libkeccak, you may to configure the dynamic linker or use LD_LIBRARY_PATH when starting sha3sum.

**Comment by hipokito** [comment]
Sorry, forgot to mention that I also ran the "sudo make install" command from libkeccak directory but I didn't provide PREFIX=/usr. Now after providing the prefix, running the command straight from the any directory still doesn't work, but I managed to get what I want by running keccak-256sum from /usr/bin directory.
