### ISSUE TITLE
Get different hash with special char

### ISSUE THREAD

**Issue by rbolog** [maandree/sha3sum#26]
Hi,
I did the following command (with an UTF8 special char):
`printf "zM3U!&OZyE5⇶bJLdV$wey" |sha3-512sum -l`
I got 

`2ff1c292bc9254695c4c522fb052f9d88d5f01b675e0cd3f84f0c449aa111d1eced01916f6e62894d9e31b7bf3423e7e0bf1ecf79ab6b7cd1cdc8bf863007532`

If I compare with some others implementation I got:
`dc380e55487376a5471ada4968853932429ac80e254a64d1430679f6e0141bc34e57f29bc967bc74fe1a58fde953adb7f7da8c01582bd1583269778d4bf01667`

If I use a ascii char string I got the same result with all implementation.

Note I have 1.1.5 version from opensuse leap 15.1

Thanks and best regards

**Comment by maandree** [comment]
I think that's because you have a `!` inside `"`-quotes (`bash: !: event not found`). With
`printf 'zM3U!&OZyE5⇶bJLdV$wey' |sha3-512sum -l` I get
`dc380e55487376a5471ada4968853932429ac80e254a64d1430679f6e0141bc34e57f29bc967bc74fe1a58fde953adb7f7da8c01582bd1583269778d4bf01667`.

**Comment by rbolog** [comment]
oh!
I did a `set +H` to disable the history substitution so I didn't have the message anymore. My mistake :-/
Thanks for your help

**Comment by maandree** [comment]
Just released you also hade a `$` as well, which is problematic.
